import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const segoeUI = localFont({
  src: [
    {
      path: "./fonts/Segoe UI/Segoe UI.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/Segoe UI/Segoe UI Italic.ttf",
      weight: "400",
      style: "italic",
    },
    {
      path: "./fonts/Segoe UI/Segoe UI Bold.ttf",
      weight: "700",
      style: "normal",
    },
    {
      path: "./fonts/Segoe UI/Segoe UI Bold Italic.ttf",
      weight: "700",
      style: "italic",
    },
  ],
  variable: "--font-segoe-ui",
});

const consolas = localFont({
  src: [
    {
      path: "./fonts/Consolas/Consolas-Regular.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/Consolas/Consolas-Italic.ttf",
      weight: "400",
      style: "italic",
    },
    {
      path: "./fonts/Consolas/Consolas-Bold.ttf",
      weight: "700",
      style: "normal",
    },
    {
      path: "./fonts/Consolas/Consolas-Bold-Italic.ttf",
      weight: "700",
      style: "italic",
    },
  ],
  variable: "--font-consolas",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${segoeUI.variable} ${consolas.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
